kumuluzee:
  name: admin-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080

  kumuluzee:
    cors-filter:
      annotations:
        my-resource:
          allow-origin: "*"
          allow-subdomains: true
          supported-methods: "GET, POST, HEAD, OPTIONS, PUT, DELETE"
  datasources:
    - jndi-name: jdbc/AdminDS
      connection-url: jdbc:postgresql://localhost:5432/image-metadata
      username: dbuser
      password: postgres
      max-pool-size: 20
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                              <Configuration name="comments">
                                  <Appenders>
                                      <Console name="console" target="SYSTEM_OUT">
                                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                      </Console>
                                      <Socket name="logstash" host="0174a08c-8d63-4e43-a5b3-855e2865241e-ls.logit.io" port="18985" protocol="udp">
                                  </Appenders>
                                  <Loggers>
                                      <!-- Default logger -->
                                      <Root level="all">
                                          <AppenderRef ref="console" level="info" />
                                          <AppenderRef ref="logstash" level="trace" />
                                      </Root>
                                  </Loggers>
                              </Configuration>'



rest-properties:
  maintenance-mode: false
admin-config:
  url:
  api-key:
  sender-mail: